"""Repository interfaces (Protocols).

Services and routers depend on these abstractions, not on the concrete
psycopg implementations (Dependency Inversion). The interfaces are kept
narrow and role-specific (Interface Segregation): a caller that only reads
stats never sees payment-write methods.

Every method takes an open psycopg cursor so the *service* owns the
transaction boundary and the repository stays stateless.
"""
from __future__ import annotations

from decimal import Decimal
from typing import Any, Protocol

Row = dict[str, Any]


class CustomerRepository(Protocol):
    def get_by_ref(self, cur, customer_ref: str) -> Row | None: ...
    def get_by_id(self, cur, customer_id: int) -> Row | None: ...
    def create(self, cur, customer_ref: str, name: str) -> Row: ...
    def list(self, cur, q: str | None, limit: int, offset: int) -> list[Row]: ...
    def count(self, cur, q: str | None) -> int: ...
    def summary(self, cur, customer_id: int) -> Row: ...


# Whitelisted sort columns for payment listing (guards against SQL injection
# via the sort parameter). Maps the public API name to a real column.
PAYMENT_SORT_COLUMNS = {
    "created_at": "t.created_at",
    "amount": "t.amount",
    "status": "t.status",
}


class PaymentFilters(Protocol):
    status: str | None
    customer_ref: str | None
    ref: str | None
    date_from: str | None
    date_to: str | None
    sort: str
    order: str


class PaymentRepository(Protocol):
    def get_by_ref(self, cur, ref: str) -> Row | None: ...
    def get_by_id(self, cur, txn_id: int) -> Row | None: ...
    def find_all_by_ref(self, cur, ref: str) -> list[Row]: ...
    def list_by_customer(self, cur, customer_id: int, limit: int, offset: int) -> list[Row]: ...
    def count_by_customer(self, cur, customer_id: int) -> int: ...
    def create(self, cur, customer_id: int, ref: str, amount: Decimal) -> Row: ...
    def callbacks_for(self, cur, txn_id: int) -> list[Row]: ...
    def list_filtered(self, cur, filters: dict, limit: int, offset: int) -> list[Row]: ...
    def count_filtered(self, cur, filters: dict) -> int: ...


class StatsRepository(Protocol):
    def status_counts(self, cur) -> dict[str, int]: ...
    def total_value(self, cur) -> Decimal: ...
    def stuck_processing_count(self, cur, minutes: int) -> int: ...
    def recent_transactions(self, cur, limit: int) -> list[Row]: ...
    def timeseries(self, cur, days: int) -> list[Row]: ...
