apiVersion: v1
kind: ConfigMap
metadata:
  name: minipay-config
  namespace: minipay
data:
  LOG_LEVEL: INFO
  APP_PORT: "8000"
  DB_HOST: minipay-db
  DB_NAME: minipay
  DB_USER: minipay
  API_UPSTREAM: minipay-api:80
